runtime: java11
entrypoint: java -Xmx64m -jar data-1.0.SNAPSHOT.jar
handlers:
  - url: /.*
    script: this field is required, but ignored

instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 1
  min_idle_instances: 1