name: CI frontend

on:
  push:
    branches: dev
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy-frontend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the project front
      run: |
        cd frontend
        yarn global add @vue/cli
        yarn install
        yarn build
    - name: Publish to netlify
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=frontend/dist --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEV_SITE_ID }}
